image: maven:3.8-openjdk-11

stages:
  - test

Simple test with allure:
  stage: test
  before_script:
    - apt-get update -qy
    - apt-get install -y wget unzip xvfb libxi6 libgconf-2-4
    - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
    - echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list
    - apt-get update -qy
    - apt-get install -y google-chrome-stable
    - wget https://chromedriver.storage.googleapis.com/$(curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE)/chromedriver_linux64.zip
    - unzip chromedriver_linux64.zip -d /usr/local/bin
    - chmod +x /usr/local/bin/chromedriver
  script:
    - xvfb-run --server-args="-screen 0 1024x768x24" mvn clean test