image: ikudinov/docker-selenide-gitlab-ci

default:
  tags:
    - docker

stages:
  - test

Simple test with allure:
  stage: test
  script:
    - docker pull ikudinov/docker-selenide-gitlab-ci
    - ./download-chrome.sh && ./run-tests.sh
    - mvn clean test

