image: selenium/standalone-chrome:115.0

stages:
  - test


Simple test with allure:
  stage: test
  before_script:
    - sudo apt install java-11-openjdk
    - sudo apt install maven
  script:
    - mvn clean test