new_job:
  image: maven:3.8.6-openjdk-11
  services:
    - docker:dind
  variables:
    SELENOID_PORT: 4444
    SELENOID_CONF: "./browsers.json"
    SELENOID_DOCKER_COMPOSE_FILE: "./docker-compose.yaml"
    DOCKER_TLS_CERTDIR: ""
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
  script:
    - apt-get update && apt-get install -y docker-compose jq
    - export DOCKER_RESOLVED_IP=$(getent ahostsv4 docker | head -n 1 | awk '{ print $1 }')
    - export SELENOID_RESOLVED_IP=172.17.0.1
    - SELENOID_HOST=http://${DOCKER_RESOLVED_IP}:${SELENOID_PORT}
    - cat ${SELENOID_CONF} | jq -r '..|.image?|strings' | xargs -I{} docker pull {}
    - echo "DOCKER_HOST=tcp://$DOCKER_RESOLVED_IP:2375" > .docker_env
    - docker-compose -f ${SELENOID_DOCKER_COMPOSE_FILE} up -d
    - sleep 5
    - docker ps -a
    - DOCKER_RESOLVED_IP=$(docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' aerokube__selenoid)
    - SELENOID_HOST=http://${DOCKER_RESOLVED_IP}:${SELENOID_PORT}
    - echo "SELENOID_HOST:${SELENOID_HOST}"
    - mvn clean test -Dselenide.remote=http://$SELENOID_RESOLVED_IP:4444/wd/hub -X
