image: maven:3.8.6-openjdk-11

stages:
  - test

Simple test with allure:
  stage: test
  before_script:
    - apt update
    - apt install -y wget
    - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    - dpkg -i google-chrome-stable_current_amd64.deb
    - google-chrome
  script:
    - mvn clean test