image: maven:3.8-openjdk-11

default:
  tags:
    - gitlab-org-docker

stages:
  - test

Simple test with allure:
  stage: test
  script:
    - mvn clean test
    - mvn allure:report
    - echo "Test started!!!"
  artifacts:
    paths:
      - target/site/allure-maven-plugin

