image: docker:latest
services:
  - docker:dind
new_job:
  image: maven:3.8.6-openjdk-11
  variables:
    SELENOID_PORT: 4444
    SELENOID_CONF: "./browsers.json"
    SELENOID_DOCKER_COMPOSE_FILE: "./docker-compose.yml"
  before_script:
    - apt-get update && apt-get install -y docker-compose
    - docker-compose up
    - sleep 5
    - docker ps -a
    - DOCKER_RESOLVED_IP=$(docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' aerokube__selenoid)
    - SELENOID_HOST=http://${DOCKER_RESOLVED_IP}:${SELENOID_PORT}
    - echo "SELENOID_HOST:${SELENOID_HOST}"
    - cat ${SELENOID_CONF} | jq -r '..|.image?|strings' | xargs -I{} docker pull {}
  script:
    - mvn clean test -Dselenide.remote=${SELENOID_HOST}/wd/hub