run selenoid:
  services:
    - docker:20-dind
  variables:
    SELENOID_PORT: 4444
    SELENOID_CONF: "./browsers.json"
    SELENOID_DOCKER_COMPOSE_FILE: "./docker-compose.yml"
    DOCKER_TLS_CERTDIR: ""
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
    WORK_DIR: "/usr/src/project"
  script:
    - apt-get update && apt-get install -y docker-compose jq curl
    - docker pull selenoid/vnc_chrome:122.0
    - docker-compose -f ${SELENOID_DOCKER_COMPOSE_FILE} up -d
    - sleep 10
    - docker ps -a
    - DOCKER_RESOLVED_IP=$(docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' live-score-fork_selenoid_1)
    - SELENOID_HOST=http://${DOCKER_RESOLVED_IP}:${SELENOID_PORT}
    - echo "SELENOID_HOST:${SELENOID_HOST}"
    - docker run -v ${PWD}:${WORK_DIR} -w ${WORK_DIR} maven:3.8.6-openjdk-11 mvn clean test -Dselenide.remote=${SELENOID_HOST}/wd/hub