image: ikudinov/docker-selenide-gitlab-ci

default:
  tags:
    - gitlab-org-docker

stages:
  - test
  - deploy

Simple test with allure:
  stage: test
  script:
    - mvn clean test
    - echo "Test started!!!"
  after_script:
    - mvn allure:report
  artifacts:
    when: always
    paths:
      - target/site/allure-maven-plugin

