image: maven:3.8.6-openjdk-11

stages:
  - test

Simple test with allure:
  stage: test
  before_script:
    - apt update
    - apt install -y wget
    - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  script:
    - mvn clean test
  after_script:
    - mvn allure:report
    - echo "Allure report - https://${CI_PROJECT_NAMESPACE}.${CI_PAGES_DOMAIN}/-/${CI_PROJECT_NAME}/-/jobs/${CI_JOB_ID}/artifacts/target/site/allure-maven-plugin/index.html"
artifacts:
      when: always
      paths:
        - target/site/allure-maven-plugin

