image: docker:latest

stages:
  - tests

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

test:
  stage: tests
  services:
    - docker:20-dind
  variables:
    SELENOID_PORT: 4444
    SELENOID_CONF: "./browsers.json"
    SELENOID_DOCKER_COMPOSE_FILE: "./docker-compose.yml"
    WORK_DIR: "/usr/src/project"
    MAVEN_CACHE: ".m2/repository/"
  script:
    - docker-compose -f ${SELENOID_DOCKER_COMPOSE_FILE} up -d selenoid
    - sleep 5
    - docker ps -a
    - DOCKER_RESOLVED_IP=$(docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' aerokube__selenoid)
    - SELENOID_HOST=http://${DOCKER_RESOLVED_IP}:${SELENOID_PORT}
    - echo "SELENOID_HOST:${SELENOID_HOST}"
    - cat ${SELENOID_CONF} | jq -r '..|.image?|strings' | xargs -I{} docker pull {}
    - |
      docker run -v ${PWD}:${WORK_DIR} -w ${WORK_DIR} maven:3.8.6-openjdk-11 \
        mvn clean test -Dremote.address=${SELENOID_HOST}/wd/hub