image: selenium/standalone-chrome:115.0

stages:
  - test

Simple test with allure:
  stage: test
  script:
    - sudo apt-get update -qy
    - sudo apt-get install -y openjdk-11-jdk maven
    - mvn clean test