version: '3'
services:
  selenoid:
    image: "aerokube/selenoid:latest-release"
    container_name: aerokube__selenoid
    network_mode: bridge
    ports:
      - "4444:4444"
    volumes:
      - ".:/etc/selenoid"
      - "./target:/output"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./target:/opt/selenoid/video"
      - "./target:/opt/selenoid/logs"
    environment:
      - "TZ=America/Los_Angeles"
      - "OVERRIDE_VIDEO_OUTPUT_DIR=./target"
    command: [ "-timeout", "10m", "-limit", "10", "-conf", "/etc/selenoid/browsers.json",
               "-video-output-dir", "/opt/selenoid/video", "-log-output-dir", "/opt/selenoid/logs" ]
  selenoid-ui:
    image: "aerokube/selenoid-ui:latest-release"
    network_mode: bridge
    depends_on:
      - selenoid
    ports:
      - "8082:8080"
    command: [ "--selenoid-uri", "http://selenoid:4444" ]
